name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: elhmn/quick-test
          ref: kuber-branch #should be kuber-release in the future
          fetch-depth: 0

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          workdir: ./app
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASE_GITHUB_TOKEN }}
